### ISSUE TITLE
Error when loading model

### ISSUE THREAD

**Issue by marl917** [leieric/Text-Sketch#1]
Hi,
 
I wanted to execute the script eval_PICS.py but I get an error when loading the model at this line: https://github.com/leieric/Text-Sketch/blob/fb348f6ce5bace1e0cd535ac94086b8de89606d0/eval_PICS.py#L170 It returns: 
<img width="431" alt="image" src="https://github.com/leieric/Text-Sketch/assets/58914469/643f806e-cd2f-40dd-9c0d-c8607b5f754b">
How to solve it ?

**Comment by leieric** [comment]
Those models are stored using Git LFS, you may need to install that. If that doesn't work, I can host them somewhere else, like google drive.

**Comment by marl917** [comment]
Thanks, i installed git LFS and it works now.
