### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by FSR3340** [leieric/Text-Sketch#2]
When running "python eval_PICS.py --data_root DATA_ROOT", I got the following wrong message:

Traceback (most recent call last):
  File "D:\FSR\Text-Sketch\eval_PICS.py", line 170, in <module>
    saved = torch.load(f'models_ntc/OneShot_{args_ntc.model_name}_CLIC_HED_{args_ntc.dist_name_model}_lmbda{args_ntc.lmbda}.pt')
  File "D:\python\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\python\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

How can I solve this problem?

**Comment by FSR3340** [comment]
> When running "python eval_PICS.py --data_root DATA_ROOT", I got the following wrong message:
> 
> Traceback (most recent call last): File "D:\FSR\Text-Sketch\eval_PICS.py", line 170, in saved = torch.load(f'models_ntc/OneShot_{args_ntc.model_name}_CLIC_HED_{args_ntc.dist_name_model}_lmbda{args_ntc.lmbda}.pt') File "D:\python\lib\site-packages\torch\serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "D:\python\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> How can I solve this problem?

**Comment by shengyenlin** [comment]
Hi FSR3340, 
could you provide your solution to this problem, please.

I also encountered the same error

**Comment by FSR3340** [comment]
you can find the answer in the closed issue#1.
Those models are stored using Git LFS, you need to use git lfs to clone the code.
